'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace myServices
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Employee", [Namespace]:="http://schemas.datacontract.org/2004/07/SampleWCFService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Employee
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpIDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmpSalaryField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpAddress() As String
            Get
                Return Me.EmpAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpAddressField, value) <> true) Then
                    Me.EmpAddressField = value
                    Me.RaisePropertyChanged("EmpAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpID() As Integer
            Get
                Return Me.EmpIDField
            End Get
            Set
                If (Me.EmpIDField.Equals(value) <> true) Then
                    Me.EmpIDField = value
                    Me.RaisePropertyChanged("EmpID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpName() As String
            Get
                Return Me.EmpNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmpNameField, value) <> true) Then
                    Me.EmpNameField = value
                    Me.RaisePropertyChanged("EmpName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmpSalary() As Integer
            Get
                Return Me.EmpSalaryField
            End Get
            Set
                If (Me.EmpSalaryField.Equals(value) <> true) Then
                    Me.EmpSalaryField = value
                    Me.RaisePropertyChanged("EmpSalary")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="myServices.IEmpService")>  _
    Public Interface IEmpService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmpService/GetAllEmployees", ReplyAction:="http://tempuri.org/IEmpService/GetAllEmployeesResponse")>  _
        Function GetAllEmployees() As System.Collections.Generic.List(Of myServices.Employee)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmpService/GetAllEmployees", ReplyAction:="http://tempuri.org/IEmpService/GetAllEmployeesResponse")>  _
        Function GetAllEmployeesAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of myServices.Employee))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmpService/AddEmployee", ReplyAction:="http://tempuri.org/IEmpService/AddEmployeeResponse")>  _
        Sub AddEmployee(ByVal emp As myServices.Employee)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEmpService/AddEmployee", ReplyAction:="http://tempuri.org/IEmpService/AddEmployeeResponse")>  _
        Function AddEmployeeAsync(ByVal emp As myServices.Employee) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEmpServiceChannel
        Inherits myServices.IEmpService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EmpServiceClient
        Inherits System.ServiceModel.ClientBase(Of myServices.IEmpService)
        Implements myServices.IEmpService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllEmployees() As System.Collections.Generic.List(Of myServices.Employee) Implements myServices.IEmpService.GetAllEmployees
            Return MyBase.Channel.GetAllEmployees
        End Function
        
        Public Function GetAllEmployeesAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of myServices.Employee)) Implements myServices.IEmpService.GetAllEmployeesAsync
            Return MyBase.Channel.GetAllEmployeesAsync
        End Function
        
        Public Sub AddEmployee(ByVal emp As myServices.Employee) Implements myServices.IEmpService.AddEmployee
            MyBase.Channel.AddEmployee(emp)
        End Sub
        
        Public Function AddEmployeeAsync(ByVal emp As myServices.Employee) As System.Threading.Tasks.Task Implements myServices.IEmpService.AddEmployeeAsync
            Return MyBase.Channel.AddEmployeeAsync(emp)
        End Function
    End Class
End Namespace
